name: Build and Push

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build-push-api-service:
    name: Build and Push Docker images for CRUD service
    runs-on: ubuntu-latest
    env:
      GITHUB_NAMESPACE: bladeart-ai
      DOCKER_NAMESPACE: bladeart
      DOCKER_REPO: bladecreate-crud
    defaults:
      run:
        working-directory: ./bladecreate

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPO }}
            ghcr.io/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_REPO }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.crud
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
